-- Migration 06 : hydratation paramétrable (coulage fixe + bassinage calculé). Idempotent.
alter table fab_recettes add column if not exists hydratation_pct numeric;
update fab_recette_lignes set quantite=0.7 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_mathis' and actif);
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.7,'kg' from fab_recettes r where r.produit_id='pr_mathis' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recettes set hydratation_pct=94 where produit_id='pr_mathis' and actif;
update fab_recette_lignes set quantite=0.8 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_khorasan' and actif);
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.8,'kg' from fab_recettes r where r.produit_id='pr_khorasan' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recettes set hydratation_pct=105 where produit_id='pr_khorasan' and actif;
update fab_recette_lignes set quantite=0.65 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_bp' and actif);
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.65,'kg' from fab_recettes r where r.produit_id='pr_bp' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recettes set hydratation_pct=85 where produit_id='pr_bp' and actif;
update fab_recette_lignes set quantite=0.7 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_tourte_meule' and actif);
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.7,'kg' from fab_recettes r where r.produit_id='pr_tourte_meule' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recettes set hydratation_pct=95 where produit_id='pr_tourte_meule' and actif;
update fab_recette_lignes set quantite=1.0 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_engrain' and actif);
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',1.0,'kg' from fab_recettes r where r.produit_id='pr_engrain' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recettes set hydratation_pct=100 where produit_id='pr_engrain' and actif;
update fab_recette_lignes set quantite=0.95 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_seigle' and actif);
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.95,'kg' from fab_recettes r where r.produit_id='pr_seigle' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recettes set hydratation_pct=95 where produit_id='pr_seigle' and actif;
update fab_recette_lignes set quantite=0.7 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_norvegien' and actif);
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.7,'kg' from fab_recettes r where r.produit_id='pr_norvegien' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recettes set hydratation_pct=100 where produit_id='pr_norvegien' and actif;
update fab_recette_lignes set quantite=0.62 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_integral' and actif);
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.62,'kg' from fab_recettes r where r.produit_id='pr_integral' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recettes set hydratation_pct=76 where produit_id='pr_integral' and actif;
update fab_recette_lignes set quantite=0.62 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_essentiel' and actif);
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.62,'kg' from fab_recettes r where r.produit_id='pr_essentiel' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recettes set hydratation_pct=82 where produit_id='pr_essentiel' and actif;
update fab_recette_lignes set quantite=0.62 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_ideal' and actif);
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.62,'kg' from fab_recettes r where r.produit_id='pr_ideal' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recettes set hydratation_pct=82 where produit_id='pr_ideal' and actif;