alter table fab_recettes add column if not exists hydratation_pct numeric;
insert into fab_recettes (produit_id,version,unite_base,rendement_base,hydratation_pct,actif) select 'pr_mathis',1,'kg de farine',1,94,true where not exists (select 1 from fab_recettes where produit_id='pr_mathis' and actif);
update fab_recettes set hydratation_pct=94 where produit_id='pr_mathis' and actif;
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_trad_bio',0.7,'kg' from fab_recettes r where r.produit_id='pr_mathis' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_trad_bio');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_khorasan',0.15,'kg' from fab_recettes r where r.produit_id='pr_mathis' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_khorasan');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_engrain',0.15,'kg' from fab_recettes r where r.produit_id='pr_mathis' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_engrain');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_sel',0.025,'kg' from fab_recettes r where r.produit_id='pr_mathis' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_sel');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levain_dur',0.275,'kg' from fab_recettes r where r.produit_id='pr_mathis' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levain_dur');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.7,'kg' from fab_recettes r where r.produit_id='pr_mathis' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recette_lignes set quantite=0.7 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_mathis' and actif);
insert into fab_recettes (produit_id,version,unite_base,rendement_base,hydratation_pct,actif) select 'pr_bp',1,'kg de farine',1,85,true where not exists (select 1 from fab_recettes where produit_id='pr_bp' and actif);
update fab_recettes set hydratation_pct=85 where produit_id='pr_bp' and actif;
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_bp',1.0,'kg' from fab_recettes r where r.produit_id='pr_bp' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_bp');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_sel',0.025,'kg' from fab_recettes r where r.produit_id='pr_bp' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_sel');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levain_dur',0.275,'kg' from fab_recettes r where r.produit_id='pr_bp' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levain_dur');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.65,'kg' from fab_recettes r where r.produit_id='pr_bp' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recette_lignes set quantite=0.65 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_bp' and actif);
insert into fab_recettes (produit_id,version,unite_base,rendement_base,hydratation_pct,actif) select 'pr_tourte_meule',1,'kg de farine',1,95,true where not exists (select 1 from fab_recettes where produit_id='pr_tourte_meule' and actif);
update fab_recettes set hydratation_pct=95 where produit_id='pr_tourte_meule' and actif;
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_seigle_t130',0.1,'kg' from fab_recettes r where r.produit_id='pr_tourte_meule' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_seigle_t130');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_t80_bise',0.9,'kg' from fab_recettes r where r.produit_id='pr_tourte_meule' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_t80_bise');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_sel',0.025,'kg' from fab_recettes r where r.produit_id='pr_tourte_meule' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_sel');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levain_dur',0.275,'kg' from fab_recettes r where r.produit_id='pr_tourte_meule' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levain_dur');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.7,'kg' from fab_recettes r where r.produit_id='pr_tourte_meule' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recette_lignes set quantite=0.7 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_tourte_meule' and actif);
insert into fab_recettes (produit_id,version,unite_base,rendement_base,hydratation_pct,actif) select 'pr_engrain',1,'kg de farine',1,100,true where not exists (select 1 from fab_recettes where produit_id='pr_engrain' and actif);
update fab_recettes set hydratation_pct=100 where produit_id='pr_engrain' and actif;
update fab_recettes set procede=$p$Pétrissage : 4 min en 1ère, 12 min en 2ème
Division : moule alu 500 g, ou 1,7 kg grands moules
Apprêt : 45 min à 1h30
Cuisson : programme Petit épeautre$p$ where produit_id='pr_engrain' and actif;
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_engrain',1.0,'kg' from fab_recettes r where r.produit_id='pr_engrain' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_engrain');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_sel',0.025,'kg' from fab_recettes r where r.produit_id='pr_engrain' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_sel');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levain_dur',0.275,'kg' from fab_recettes r where r.produit_id='pr_engrain' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levain_dur');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levure',0.007,'kg' from fab_recettes r where r.produit_id='pr_engrain' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levure');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',1.0,'kg' from fab_recettes r where r.produit_id='pr_engrain' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recette_lignes set quantite=1.0 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_engrain' and actif);
insert into fab_recettes (produit_id,version,unite_base,rendement_base,hydratation_pct,actif) select 'pr_seigle',1,'kg de farine',1,95,true where not exists (select 1 from fab_recettes where produit_id='pr_seigle' and actif);
update fab_recettes set hydratation_pct=95 where produit_id='pr_seigle' and actif;
update fab_recettes set procede=$p$Pétrissage : 5 min en 1ère, 2 min en 2ème
Pointage : 45 min
Division : 1 kg, bouler en banneton
Apprêt : 30 à 45 min
Cuisson : 270°C beaucoup de buée, four tombant$p$ where produit_id='pr_seigle' and actif;
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_seigle_t130',1.0,'kg' from fab_recettes r where r.produit_id='pr_seigle' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_seigle_t130');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_sel',0.025,'kg' from fab_recettes r where r.produit_id='pr_seigle' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_sel');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levain_dur',0.275,'kg' from fab_recettes r where r.produit_id='pr_seigle' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levain_dur');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levure',0.005,'kg' from fab_recettes r where r.produit_id='pr_seigle' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levure');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.95,'kg' from fab_recettes r where r.produit_id='pr_seigle' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recette_lignes set quantite=0.95 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_seigle' and actif);
insert into fab_recettes (produit_id,version,unite_base,rendement_base,hydratation_pct,actif) select 'pr_integral',1,'kg de farine',1,76,true where not exists (select 1 from fab_recettes where produit_id='pr_integral' and actif);
update fab_recettes set hydratation_pct=76 where produit_id='pr_integral' and actif;
update fab_recettes set procede=$p$Pétrissage : 4 min en 1ère, 6 min en 2ème
Pesage : bac 7,2 à 7,6 kg
Pointage : 1h30 à 2h + RABAT puis frigo 2°C
Division : 20 pièces, batard
Apprêt : 50 min à 1h30
Cuisson : programme Pain 500 g$p$ where produit_id='pr_integral' and actif;
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_trad_bio',0.1,'kg' from fab_recettes r where r.produit_id='pr_integral' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_trad_bio');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_t150',0.9,'kg' from fab_recettes r where r.produit_id='pr_integral' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_t150');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_sel',0.025,'kg' from fab_recettes r where r.produit_id='pr_integral' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_sel');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levain_liquide',0.2,'kg' from fab_recettes r where r.produit_id='pr_integral' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levain_liquide');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.62,'kg' from fab_recettes r where r.produit_id='pr_integral' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recette_lignes set quantite=0.62 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_integral' and actif);
insert into fab_recettes (produit_id,version,unite_base,rendement_base,hydratation_pct,actif) select 'pr_essentiel',1,'kg de farine',1,82,true where not exists (select 1 from fab_recettes where produit_id='pr_essentiel' and actif);
update fab_recettes set hydratation_pct=82 where produit_id='pr_essentiel' and actif;
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_trad_bio',0.7,'kg' from fab_recettes r where r.produit_id='pr_essentiel' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_trad_bio');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_t150',0.15,'kg' from fab_recettes r where r.produit_id='pr_essentiel' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_t150');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_seigle_t130',0.15,'kg' from fab_recettes r where r.produit_id='pr_essentiel' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_seigle_t130');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_sel',0.025,'kg' from fab_recettes r where r.produit_id='pr_essentiel' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_sel');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levain_liquide',0.2,'kg' from fab_recettes r where r.produit_id='pr_essentiel' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levain_liquide');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.62,'kg' from fab_recettes r where r.produit_id='pr_essentiel' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recette_lignes set quantite=0.62 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_essentiel' and actif);
insert into fab_recettes (produit_id,version,unite_base,rendement_base,hydratation_pct,actif) select 'pr_ideal',1,'kg de farine',1,82,true where not exists (select 1 from fab_recettes where produit_id='pr_ideal' and actif);
update fab_recettes set hydratation_pct=82 where produit_id='pr_ideal' and actif;
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_trad_bio',0.7,'kg' from fab_recettes r where r.produit_id='pr_ideal' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_trad_bio');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_t150',0.15,'kg' from fab_recettes r where r.produit_id='pr_ideal' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_t150');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_seigle_t130',0.15,'kg' from fab_recettes r where r.produit_id='pr_ideal' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_seigle_t130');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_graines',0.1,'kg' from fab_recettes r where r.produit_id='pr_ideal' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_graines');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_sel',0.025,'kg' from fab_recettes r where r.produit_id='pr_ideal' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_sel');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levain_liquide',0.2,'kg' from fab_recettes r where r.produit_id='pr_ideal' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levain_liquide');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.62,'kg' from fab_recettes r where r.produit_id='pr_ideal' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recette_lignes set quantite=0.62 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_ideal' and actif);
insert into fab_recettes (produit_id,version,unite_base,rendement_base,hydratation_pct,actif) select 'pr_khorasan',1,'kg de farine',1,105,true where not exists (select 1 from fab_recettes where produit_id='pr_khorasan' and actif);
update fab_recettes set hydratation_pct=105 where produit_id='pr_khorasan' and actif;
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_trad_bio',0.1,'kg' from fab_recettes r where r.produit_id='pr_khorasan' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_trad_bio');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_khorasan',0.9,'kg' from fab_recettes r where r.produit_id='pr_khorasan' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_khorasan');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_sel',0.025,'kg' from fab_recettes r where r.produit_id='pr_khorasan' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_sel');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levain_dur',0.275,'kg' from fab_recettes r where r.produit_id='pr_khorasan' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levain_dur');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.8,'kg' from fab_recettes r where r.produit_id='pr_khorasan' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recette_lignes set quantite=0.8 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_khorasan' and actif);
insert into fab_recettes (produit_id,version,unite_base,rendement_base,hydratation_pct,actif) select 'pr_norvegien',1,'kg de farine',1,100,true where not exists (select 1 from fab_recettes where produit_id='pr_norvegien' and actif);
update fab_recettes set hydratation_pct=100 where produit_id='pr_norvegien' and actif;
update fab_recettes set procede=$p$Pétrissage : 5 min en 1ère puis 7 min en 2ème
Division : moule de 1,1 kg
Apprêt : 45 min à 1h30
Cuisson : programme Petit épeautre$p$ where produit_id='pr_norvegien' and actif;
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_seigle_t130',0.25,'kg' from fab_recettes r where r.produit_id='pr_norvegien' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_seigle_t130');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_t80_bise',0.75,'kg' from fab_recettes r where r.produit_id='pr_norvegien' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_t80_bise');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_graines',0.4,'kg' from fab_recettes r where r.produit_id='pr_norvegien' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_graines');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_sel',0.025,'kg' from fab_recettes r where r.produit_id='pr_norvegien' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_sel');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levain_dur',0.275,'kg' from fab_recettes r where r.produit_id='pr_norvegien' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levain_dur');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_levure',0.01,'kg' from fab_recettes r where r.produit_id='pr_norvegien' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_levure');
insert into fab_recette_lignes (recette_id,ingredient_id,quantite,unite) select r.id,'ing_eau',0.7,'kg' from fab_recettes r where r.produit_id='pr_norvegien' and r.actif and not exists (select 1 from fab_recette_lignes l where l.recette_id=r.id and l.ingredient_id='ing_eau');
update fab_recette_lignes set quantite=0.7 where ingredient_id='ing_eau' and recette_id in (select id from fab_recettes where produit_id='pr_norvegien' and actif);